apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzadel-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizzadel
  template:
    metadata:
      labels:
        app: pizzadel
    spec:
      containers:
      - name: pizzadel-app
        image: your-dockerhub-username/pizzadel:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: pizzadel-config
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config