apiVersion: v1
kind: Service
metadata:
  name: pizza-site-service
spec:
  type: LoadBalancer
  selector:
    app: pizza-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
