# Generated by Django 5.1.7 on 2025-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_address_alter_customuser_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Этаж'),
        ),
    ]
